image: python:3.10

pipelines:
  default:
    - step:
        name: Build and Test Django
        caches:
          - pip
        script:
          - pip install -r requirements.txt
          - python manage.py test
